### ISSUE TITLE
error creating env0 reources

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#363]
Some resources gets created fine while other resources throws errors

> /opt/tfenv/bin/terraform apply -auto-approve /tmp/4efb0c53-836c-4bf4-a6e1-a7ed2a663d4c/.env0workdir/.tf-plan

env0_project.project: Creating...

env0_project.project: Creation complete after 4s [id=d57c73d5-ad58-4e2f-9e1c-3d1a134fdc4d]

env0_configuration_variable.dev_team_access_dropdown[0]: Creating...

env0_configuration_variable.base_name_dropdown[0]: Creating...
env0_cloud_credentials_project_assignment.example: Creating...

env0_configuration_variable.drift_detection_dropdown[0]: Creating...

env0_configuration_variable.project_topic_dropdown[0]: Creating...
env0_configuration_variable.admin_team_name_dropdown[0]: Creating...
env0_configuration_variable.project_type_dropdown[0]: Creating...

env0_configuration_variable.admin_team_access_dropdown[0]: Creating...
env0_configuration_variable.dev_team_name_dropdown[0]: Creating...

╷
│ Error: Request cancelled
│ 
│   with env0_configuration_variable.admin_team_name_dropdown[0],
│   on main.tf line 8, in resource "env0_configuration_variable" "admin_team_name_dropdown":
│    8: resource "env0_configuration_variable" "admin_team_name_dropdown" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

╷
│ Error: Request cancelled
│ 
│   with env0_configuration_variable.dev_team_name_dropdown[0],
│   on main.tf line 18, in resource "env0_configuration_variable" "dev_team_name_dropdown":
│   18: resource "env0_configuration_variable" "dev_team_name_dropdown" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with env0_configuration_variable.admin_team_access_dropdown[0],
│   on main.tf line 28, in resource "env0_configuration_variable" "admin_team_access_dropdown":
│   28: resource "env0_configuration_variable" "admin_team_access_dropdown" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.dev_team_access_dropdown[0],
│   on main.tf line 38, in resource "env0_configuration_variable" "dev_team_access_dropdown":
│   38: resource "env0_configuration_variable" "dev_team_access_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Request cancelled
│ 
│   with env0_configuration_variable.project_type_dropdown[0],
│   on main.tf line 48, in resource "env0_configuration_variable" "project_type_dropdown":
│   48: resource "env0_configuration_variable" "project_type_dropdown" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.drift_detection_dropdown[0],
│   on main.tf line 58, in resource "env0_configuration_variable" "drift_detection_dropdown":
│   58: resource "env0_configuration_variable" "drift_detection_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.base_name_dropdown[0],
│   on main.tf line 68, in resource "env0_configuration_variable" "base_name_dropdown":
│   68: resource "env0_configuration_variable" "base_name_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.project_topic_dropdown[0],
│   on main.tf line 78, in resource "env0_configuration_variable" "project_topic_dropdown":
│   78: resource "env0_configuration_variable" "project_topic_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_cloud_credentials_project_assignment.example,
│   on main.tf line 99, in resource "env0_cloud_credentials_project_assignment" "example":
│   99: resource "env0_cloud_credentials_project_assignment" "example" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-env0_v1.0.2 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 137 [running]:
github.com/env0/terraform-provider-env0/env0.getEnum(0xdab000?, {0x0, 0x0})
	github.com/env0/terraform-provider-env0/env0/resource_configuration_variable.go:198 +0x3b9
github.com/env0/terraform-provider-env0/env0.resourceConfigurationVariableCreate({0xf985a8?, 0xc000629180?}, 0xcee5a0?, {0xde35e0?, 0xc000089300})
	github.com/env0/terraform-provider-env0/env0/resource_configuration_variable.go:164 +0x37e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000199800, {0xf985a8, 0xc000629180}, 0x2?, {0xde35e0, 0xc000089300})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:285 +0x1a3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000199800, {0xf985a8, 0xc000629180}, 0xc000433dc0, 0xc000275d60, {0xde35e0, 0xc000089300})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:396 +0x6ef
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000304330, {0xf985a8, 0xc000629180}, 0xc0006d4be0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000121fc0, {0xf98650?, 0xc0004bb5f0?}, 0xe?)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdae860?, 0xc000121fc0}, {0xf98650, 0xc0004bb5f0}, 0xc0006cf200, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032b880, {0xf9b728, 0xc000212480}, 0xc00013ce00, 0xc000250870, 0x14cbae0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00032b880, {0xf9b728, 0xc000212480}, 0xc00013ce00, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-env0_v1.0.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by chris-ackerman-dentsu** [comment]
duplicate issue of [https://github.com/env0/terraform-provider-env0/issues/364](url)
