### ISSUE TITLE
error creating env0 reources

### ISSUE THREAD

**Issue by chris-ackerman-dentsu** [env0/terraform-provider-env0#364]
Some resources gets created fine while other resources throws errors

> /opt/tfenv/bin/terraform apply -auto-approve /tmp/1d6aab7c-266d-46ad-a8eb-a7f8af4f5050/.env0workdir/.tf-plan

env0_configuration_variable.base_name_dropdown[0]: Creating...

env0_configuration_variable.drift_detection_dropdown[0]: Creating...
env0_configuration_variable.dev_team_name_dropdown[0]: Creating...

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.admin_team_name_dropdown[0],
│   on main.tf line 8, in resource "env0_configuration_variable" "admin_team_name_dropdown":
│    8: resource "env0_configuration_variable" "admin_team_name_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain
│ more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.dev_team_name_dropdown[0],
│   on main.tf line 18, in resource "env0_configuration_variable" "dev_team_name_dropdown":
│   18: resource "env0_configuration_variable" "dev_team_name_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.drift_detection_dropdown[0],
│   on main.tf line 58, in resource "env0_configuration_variable" "drift_detection_dropdown":
│   58: resource "env0_configuration_variable" "drift_detection_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

╷
│ Error: Plugin did not respond
│ 
│   with env0_configuration_variable.base_name_dropdown[0],
│   on main.tf line 68, in resource "env0_configuration_variable" "base_name_dropdown":
│   68: resource "env0_configuration_variable" "base_name_dropdown" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-env0_v1.0.2 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 71 [running]:
github.com/env0/terraform-provider-env0/env0.getEnum(0xd0?, {0x0, 0x0})
	github.com/env0/terraform-provider-env0/env0/resource_configuration_variable.go:198 +0x3b9
github.com/env0/terraform-provider-env0/env0.resourceConfigurationVariableCreate({0xf985a8?, 0xc000335380?}, 0xcee5a0?, {0xde35e0?, 0xc000340c80})
	github.com/env0/terraform-provider-env0/env0/resource_configuration_variable.go:164 +0x37e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001b5800, {0xf985a8, 0xc000335380}, 0x2?, {0xde35e0, 0xc000340c80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:285 +0x1a3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001b5800, {0xf985a8, 0xc000335380}, 0xc0003bac40, 0xc000491020, {0xde35e0, 0xc000340c80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:396 +0x6ef
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000132f18, {0xf985a8, 0xc000335380}, 0xc00071cdc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:955 +0x9aa
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00038e440, {0xf98650?, 0xc0006e2d80?}, 0x0?)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdae860?, 0xc00038e440}, {0xf98650, 0xc0006e2d80}, 0xc000698540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e2e00, {0xf9b728, 0xc0004de180}, 0xc00033e500, 0xc000591d40, 0x14cbae0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0002e2e00, {0xf9b728, 0xc0004de180}, 0xc00033e500, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x28a

Error: The terraform-provider-env0_v1.0.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by chris-ackerman-dentsu** [comment]
I figured out why this happens.
I was trying to add a empty option to the enum list and it crashes the plugin:

`drift_detection_defaults = [
    "",
    "*/5 * * * *",
    "*/10 * * * *"
  ]
`

removing the empty string so it became:
`drift_detection_defaults = [
    "*/5 * * * *",
    "*/10 * * * *"
  ]
`
fixed the problem.
